### ISSUE TITLE
caught exception while joining a map

### ISSUE THREAD

**Issue by pessiuff** [4wi/i_was_coding_this_while_drunk#12]
i managed to debug it and the exception results are "Exception thrown at 0x2D866E0D (client.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x00000088." tried to find the location 0x2D866E0D in memory but didn't find anything. if anyone has any idea it would be good to share with each other.

**Comment by violanes** [comment]
0x2D866E0D is in bounds of mapped client.dll, to obtain crash address and its semantics you would need to look at stack trace and find out where hack pushes incorrect arguments or redirects to invalid eip (might be jmp, call, ret instructions). Also I'd recommend you using VEH debugger (like x64dbg) instead of VS SEH.

Good luck on your further researches, feel free to contribute!

**Comment by pessiuff** [comment]
> 0x2D866E0D is in bounds of mapped client.dll, to obtain crash address and its semantics you would need to look at stack trace and find out where hack pushes incorrect arguments or redirects to invalid eip (might be jmp, call, ret instructions). Also I'd recommend you using VEH debugger (like x64dbg) instead of VS SEH.
> 
> Good luck on your further researches, feel free to contribute!

thanks i think i got it : )

**Comment by DiogoDuart3** [comment]
@pessiuff how did u fixed it?

**Comment by pessiuff** [comment]
> @pessiuff how did u fixed it?

i didn't fix it yet i will debug using a veh debugger when i have time and figure out what actually crashes and if i fix it, i will reopen this again.
